### ISSUE TITLE
How to custom shortcut key?

### ISSUE THREAD

**Issue by Le0v1n** [ruzrobert/ShowDesktopOneMonitor#11]
I have no idea about C#, so how to custom shortcut key. Now the shortcut is `Windows -> Shift -> D`, `Shift -> Windows -> D` doesn't work :joy:. I wanna use `Windows + D` actually. 😄

**Comment by Le0v1n** [comment]
I found the actual shortcut is `Shift + D`, it's bad 😢

**Comment by M76chao** [comment]
+1

**Comment by ruzrobert** [comment]
Hello guys, sorry I don't have much time to maintain this repo. I hope to get back after a few weeks.
Actually, we already have a configurable shortcut key, contributed by another user. This change is Not available yet in the Releases section - I need to rebuild the project and make a new Release.

**Comment by ruzrobert** [comment]
@Le0v1n have you tried to start the program with Admin rights + disabling the antivirus? "Windows" key might be blocked by the system/antivirus, especially if there are no admin rights.

Are you on Win 10 or Win 11 by the way?

**Comment by Le0v1n** [comment]
@ruzrobert 
Thanks for your selfless dedication, the system operation of mine is Windows 10.
