### ISSUE TITLE
Please release a new distribution version

### ISSUE THREAD

**Issue by M76chao** [ruzrobert/ShowDesktopOneMonitor#14]
I am not a programmer. And live in China. Compiling your source code is too complicated.

Please publish a program that can run directly after downloading, even if you compile the program and put it in the source code. Thank you very much!

**Comment by ruzrobert** [comment]
Hi @M76chao , you can access the last stable build in the Releases section here: https://github.com/ruzrobert/ShowDesktopOneMonitor/releases
