### ISSUE TITLE
not work on win11 from now on

### ISSUE THREAD

**Issue by Beingo** [ruzrobert/ShowDesktopOneMonitor#8]

**Comment by ruzrobert** [comment]
Hey @Beingo, I expect Windows 11 has changed some of their APIs, and the app might stop working :(
I am not planning to upgrade for now, but maybe @PrOF-kk would like to check for a possible solution, if he has time :)

**Comment by PrOF-kk** [comment]
Hey, my computers run either Windows 10 or Linux, so I cannot do anything about it until I upgrade to Windows 11, which I'm not planning to do anytime soon

**Comment by furopi** [comment]
Strange for me it's working fine on Win 11 Pro (Insider Preview ver., Dev Channel). Maybe you did something wrong during setup...

**Comment by ruzrobert** [comment]
Hey @furopi , thanks for letting us know that it works! I'm still on Win 10 and not planning to upgrade for now, but I am glad to know that life of this app might not end on Win 10 :)

**Comment by furopi** [comment]
You're Welcome! No problem! 😎

**Comment by ruzrobert** [comment]
Closing this issue as it works on Win 11

**Comment by ruzrobert** [comment]
Closing this issue as it works on Win 11
